### PR TITLE
Paper organiser 

### PR DESCRIPTION
**Pull request by DarkStarStrix**
Here, Review it and check everything that is there

### CODE REVIEW

**Comment by DarkStarStrix** [comment]
Hopefully, this is accurate it's exceptionally long

**Review by mgg39 — CHANGES_REQUESTED** [review]
Hi @DarkStarStrix this is amazing work, thank you! Although it does not contain all papers (the list is indeed quite long). I think this addition would be great at the beginning of the README but I would rather not delete the links and access to all the other papers. A way to avoid this would be to follow up this text with the full list. Could you append this before I approve it? Thank you again for your contribution :)

**Comment by DarkStarStrix** [comment]
Hey maria thanks for the prompt response Can you point out the papers I missed? I'm struggling to read them; it's too long I can immediately add them if you can help out.

**Comment by mgg39** [comment]
`The following papers/articles/books are available in this repo (in order):
- Quantum networking, by  Rodney Van Meter (book)
- Schrödinger's Web: Race to Build the Quantum Internet, by Jonathan Dowling (book)
- 2D materials for quantum information science
       https://www.nature.com/articles/s41578-019-0136-x
- A Grand Unification of Quantum Algorithms - John M. Martyn, Zane M. Rossi, Andrew K. Tan, Isaac L. Chuang
       https://arxiv.org/abs/2105.02859
- A Preprocessing Perspective for Quantum Machine Learning Classification Advantage in Finance Using NISQ Algorithms - Javier Mancilla, Christophe Pere 
       https://www.mdpi.com/1099-4300/24/11/1656
- A Review of Quantum Computer Energy Efficiency - Nelly Elsayed† Anthony S. Maida† Magdy Bayoumi
       https://ieeexplore.ieee.org/abstract/document/8767125
- A Tutorial on Quantum Error Correction - Andrew M. Steane
       https://www2.physics.ox.ac.uk/sites/default/files/ErrorCorrectionSteane06.pdf
- A generalization of the stabilizer formalism for simulating arbitrary quantum circuits - Theodore J. Yoder   
       https://www.scottaaronson.com/showcase2/report/ted-yoder.pdf
- A photonic cluster state machine gun - Netanel H. Lindner, Terry Rudolph
       https://arxiv.org/abs/0810.2587
- A quantum walk control plane for distributed quantum computing in quantum networks - Matheus Guedes de Andrade, Wenhan Dai, Saikat Guha, Don Towsley
       https://arxiv.org/abs/2106.09839
- Advances in Silicon Quantum Photonics - Jeremy C. Adcock; Jueming Bao; Yulin Chi; Xiaojiong Chen; Davide Bacco; Qihuang
       https://ieeexplore.ieee.org/document/9205209/authors#authors
- Advantages and Bottlenecks of Quantum Machine Learning for Remote Sensing - Daniela A. Zaidenberg, Alessandro Sebastianelli, Dario Spiller, Bertrand Le Saux, Silvia Liberata Ullo https://arxiv.org/abs/2101.10657 or https://ieeexplore.ieee.org/document/9553133
- All-photonic quantum repeaters - Koji Azuma, Kiyoshi Tamaki & Hoi-Kwong Lo
       https://arxiv.org/abs/1309.7207
- An Architecture for Meeting Quality-of-Service Requirements in Multi-User Quantum Networks - Matthew Skrzypczyk, Stephanie Wehner
       https://arxiv.org/abs/2111.13124
- An energy efficient multipliers using reversible gates
       https://www.researchgate.net/publication/347857423_An_energy_efficient_multipliers_using_reversible_gates
- An introduction to measurement based quantum computation - Richard Jozsa
       https://arxiv.org/abs/quant-ph/0508124
- Anti-Hong-Ou-Mandel effect with entangled photons - Anton N. Vetlugin, Ruixiang Guo, Cesare Soci, Nikolay I. Zheludev
       https://arxiv.org/abs/2105.05444
- Assembly and coherent control of a register of nuclear spin qubits
       https://arxiv.org/abs/2108.04790
- Automated distribution of quantum circuits via hypergraph partitioning - Pablo Andrés-Martínez, Chris Heunen
       https://arxiv.org/abs/1811.10972
- Blueprint for a Scalable Photonic Fault-Tolerant Quantum Computer - J. Eli Bourassa, Rafael N. Alexander, Michael Vasmer, Ashlesha Patil, ...
       https://arxiv.org/abs/2010.02905
- Channel Waveguides in Lithium Niobate and Lithium Tantalate- Yi Lu, Benjamin Johnston, Peter Dekker, Michael J Withford, Judith M Dawes
       https://pubmed.ncbi.nlm.nih.gov/32867367/
- Classical, quantum and total correlations - L Henderson and V Vedral
       https://iopscience.iop.org/article/10.1088/0305-4470/34/35/315
- Coherent shuttle of electron-spin states - T. Fujita, T. A. Baart, C. Reichl, W. Wegscheider, L. M. K. Vandersype
       https://arxiv.org/abs/1701.00815
- Commercial applications of quantum computing - Francesco Bova, Avi Goldfarb, Roger G. Melko
       https://epjquantumtechnology.springeropen.com/articles/10.1140/epjqt/s40507-021-00091-1
- Constructor Theory of Information - David Deutsch, Chiara Marletto
       https://arxiv.org/abs/1405.5563
- Constructor Theory of Life - Chiara Marletto
       https://arxiv.org/abs/1407.0681
- Constructor Theory of Probability
       https://arxiv.org/abs/1507.03287
- Constructor Theory of Thermodynamics - Chiara Marletto
       https://arxiv.org/abs/1608.02625
- Continued Fractions and Probability Estimations in Shor’s Algorithm: A Detailed and Self-Contained Treatise -Johanna Barzen and Frank Leymann
       https://arxiv.org/abs/2205.01925
- Designing a Quantum Network Protocol - Wojciech Kozlowski, Axel Dahlberg, Stephanie Wehner
       https://arxiv.org/abs/2010.02575
- Discrete simulation of quantum walks - Madita Willsch, Dennis Willsch, Kristel Michielsen, and Hans De Raedt
       https://www.frontiersin.org/articles/10.3389/fphy.2020.00145/full
- Disentangling Hype from Practicality: On Realistically Achieving Quantum Advantage - Torsten Hoefler, Thomas Haner and Matthias Troyer
       https://arxiv.org/pdf/2307.00523.pdf
- Distribution of entanglement in large-scale quantum networks - S Perseguers, G J Lapeyre Jr, D Cavalcanti, M Lewenstein and A Acin
       https://iopscience.iop.org/article/10.1088/0034-4885/76/9/096001/pdf
- Does provable absence of barren plateaus imply classical simulability? Or, why we need to rethink variational quantum computing - M. Cerezo et. al.
       https://arxiv.org/pdf/2312.09121.pdf
- Efficient parametric frequency conversion in lithium niobate nanophotonic chips - Jia-yang Chen, Yong Meng Sua, Zhao-hui Ma, Chao Tang, Zhan Li, Yu-ping Huang
       https://arxiv.org/abs/1903.08722
- Elementary gates for quantum computation - Adriano Barenco, Charles H. Bennett, Richard Cleve, David P. DiVincenzo, ...
       https://journals.aps.org/pra/abstract/10.1103/PhysRevA.52.3457?cm_mc_uid=43781767191014577577895&cm_mc_sid_50200000=1460741020
- Energy-Efficient Superconducting Computing—Power Budgets and Requirements
       https://ieeexplore.ieee.org/abstract/document/6449287
- Error Correcting Codes in Quantum Theory, Andrew Steane
       https://users.physics.ox.ac.uk/~Steane/pubs/Steane_PRL95.pdf 
- Energy-Efficient Superconducting Computing—Power Budgets and Requirements
       https://ieeexplore.ieee.org/abstract/document/6449287
- Energy & Information - Myron Tribus and Edward C. McIrvine
       https://www.jstor.org/stable/24923125?saml_data=eyJzYW1sVG9rZW4iOiIzYThiNDZlMi1iZGVhLTRlMGQtOGExOC03YzQ2ZDZkNzQyNWQiLCJpbnN0aXR1dGlvbklkcyI6WyJiN2JlMjYxZS1hOWVhLTRiZGYtOWVjNS00ZWVkN2NhNTI5NzIiXX0#metadata_info_tab_contents
- Establishing the quantum supremacy frontier with a 281 Pflop/s simulation
       https://iopscience.iop.org/article/10.1088/2058-9565/ab7eeb/pdf?casa_token=fqUuMeRiHW8AAAAA:-qCFEf4B8q71vIHgiBtzWC_CMtpzILLTB5PaGoVOSn-EugRt6crwFnEY65HH3AwY_zVOkq2gmQ
- Experimental demonstration of memory-enhanced quantum communication - Mihir K. Bhaskar, Ralf Riedinger, Bartholomeus Machielse, David S. Levonian,...
       https://arxiv.org/abs/1909.01323
- Experimental Estimation of Quantum State Properties from Classical Shadows - G.I. Struchalin, Ya.A. Zagorovskii, E.V. Kovlakov, S.S.Straupe, S.P. Kulik
       https://arxiv.org/abs/2008.05234 
- Experimental exploration of five-qubit quantum error-correcting code with superconducting qubits - Ming Gong, Xiao Yuan, Shiyu Wang, Yulin Wu, ...
       https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiH6f7Sk8n5AhW6S0EAHYpcCL0QFnoECAsQAQ&url=https%3A%2F%2Fora.ox.ac.uk%2Fobjects%2Fuuid%3A5b2e5204-7746-4569-807e-77654a77313a%2Ffiles%2Fs0v838175c&usg=AOvVaw3l2-7GFf0m6Fw14IpYljjx
- Experimental violation of Bell inequalities for multi-dimensional systems - Hsin-Pin Lo1, Che-Ming Li2, AtsushiYabushita1, Yueh-NanChen3, Chih-Wei Luo1 & Takayoshi Kobayashi
       https://www.nature.com/articles/srep22088
- Fault-tolerant Preparation of Stabilizer States for Quantum CSS Codes by Classical Error-Correcting Codes - Ching-Yi Lai, Yi-Cong Zheng, and Todd A. Brun
       https://arxiv.org/abs/1605.05647
- Field-Deployable Quantum Memory for Quantum Networking - Yang Wang, Alexander N. Craddock, Rourke Sekelsky, Mael Flament, and Mehdi Namazi
       https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.18.044058
- Field-linked resonances of polar molecules
       https://www.nature.com/articles/s41586-022-05651-8
- Five open problems in theory of quantum information - Paweł Horodecki, Łukasz Rudnicki, Karol Życzkowski
       https://arxiv.org/abs/2002.03233
- Foundations for Near-Term Quantum Natural Language Processing - Bob Coecke, Giovanni de Felice, Konstantinos Meichanetzidis, Alexis Toumi
       https://arxiv.org/abs/2012.03755
- Fundamental Principle of Information-to-Energy Conversion - Antonio Alfonso-Faus
       https://arxiv.org/abs/1401.6052
- Fusion-based quantum computation - Sara Bartolucci, Patrick Birchall, Hector Bombin, Hugo Cable, Chris Dawson, Mercedes Gimeno-Segovia, Eric Johnston, ...
       https://arxiv.org/abs/2101.09310
- Gate Set Tomography - Erik Nielsen, John King Gamble, Kenneth Rudinger, Travis Scholten, Kevin Young1, and Robin Blume-Kohout
       https://arxiv.org/abs/2009.07301
- Generalized GHZ States and Distributed Quantum - Anocha Yimsiriwattana, Samuel J. Lomonaco Jr
       https://arxiv.org/abs/quant-ph/0402148
- Generation of broadband correlated photon-pairs in short thin-film lithium-niobate waveguides - Bradley S. Elkus, et. al
       https://opg.optica.org/directpdfaccess/02ed958b-dc38-449c-b5d94c4360c660b2_424684/oe-27-26-38521.pdf?da=1&id=424684&seq=0&mobile=no 
- High Quality Entangled Photon Pair Generation in Periodically Poled Thin-Film Lithium Niobate Waveguides - Jie Zhao, Chaoxuan Ma, Michael Rüsing, and Shayan Mookherjea
       https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.124.163603 
- How many qubits are needed for quantum computational supremacy? - Alexander M. Dalzell1, Aram W. Harrow, Dax Enshan Koh, and Rolando L. La Placa 
       https://quantum-journal.org/papers/q-2020-05-11-264/
- Implementation of multidimensional quantum walks using linear optics and classical light - Sandeep K. Goyal, Filippus S. Roux, Andrew Forbes, and Thomas Konrad
       https://journals.aps.org/pra/abstract/10.1103/PhysRevA.92.040302
- Implementing Post-quantum Cryptography for Developers - Julius Hekkala, Kimmo Halunen and Visa Vallivaara
       https://www.scitepress.org/Papers/2022/107862/107862.pdf
- Implementing the quantum random walk - B. C. Travaglione, G. J. Milburn
       https://arxiv.org/abs/quant-ph/0109076
- Is quantum computing green? An estimate for an energy-efficiency quantum advantage - Daniel Jaschke and Simone Montangero
       https://arxiv.org/pdf/2205.12092.pdf
- lambeq: An Efficient High-Level Python Library for Quantum NLP - Dimitri Kartsaklis, Ian Fan, Richie Yeung, Anna Pearson, Robin Lorenz,...
       https://arxiv.org/abs/2110.04236
- Linear growth of quantum circuit complexity, by Jonas Haferkamp, Philippe Faist , Naga B. T. Kothakonda, Jens Eisert, and Nicole Yunger Halpern.
       https://www.nature.com/articles/s41567-022-01539-6
- Memory cost of quantum protocols - Alessandro Bisio, Giacomo Mauro D’Ariano, and Paolo Perinott
       https://www.researchgate.net/publication/51965796_Memory_cost_of_quantum_protocols
- Microwave Quantum Memristors - X.-Y. Qiu, S. Kumar, F. A. Cárdenas-López, G. Alvarado Barrios, E. Solano, F.Albarrán-Arriagada
       https://arxiv.org/abs/2311.06925
- Mitigating the quantum hype - Olivier Ezratty
       https://arxiv.org/abs/2202.01925
- Mitiq: A software package for error mitigation on noisy quantum computers - Ryan LaRose, Andrea Mari, Sarah Kaiser, Peter J. Karalekas, Andre A. Alves, ...
       https://arxiv.org/abs/2009.04417
- Multi-state quantum simulations via model-space quantum imaginary time evolution - Takashi Tsuchimochi, Yoohee Ryo, Siu Chung Tsang, Seiichiro L. Ten-no
       https://arxiv.org/abs/2206.04494
- Multiple Particle Interference and Quantum Error Correction, Andrew Steane
       https://arxiv.org/abs/quant-ph/9601029
- Multiple Particle Interference and Quantum Error Correction - Andrew Steane 
       https://arxiv.org/abs/quant-ph/9601029Multiplexed quantum repeaters
- Multiplexed quantum repeaters based on dual-species trapped-ion systems - Prajit Dhara, Norbert M. Linke, Edo Waks, Saikat Guha, Kaushik P. Seshadreesan
       https://arxiv.org/abs/2105.06707
- NetSquid, a NETwork Simulator for QUantum Information using Discrete events - Tim Coopmans, Robert Knegjens, Axel Dahlberg, David Maier, Loek Nijsten, ...
       https://arxiv.org/abs/2010.12535
- On Circuit-based Hybrid Quantum Neural Networks for Remote Sensing Imagery Classification - Alessandro Sebastianelli, Daniela A. Zaidenberg, Dario Spiller, Bertrand Le Saux, Silvia Liberata Ullo https://arxiv.org/abs/2109.09484 or https://ieeexplore.ieee.org/document/9647979
- On the CNOT-cost of TOFFOLI gates - Vivek V. Shende, Igor L. Markov
       https://dl.acm.org/doi/10.5555/2011791.2011799
- One-Dimensional Quantum Walks - Andris Ambainis, Eric Bach, Ashwin Nayak, Ashvin Vishwanath, John Watrous
       https://dl.acm.org/doi/10.1145/380752.380757
- Optimal architectures for long distance quantum communication - Sreraman Muralidharan, Linshu Li, Jungsang Kim, Norbert Lütkenhaus, Mikhail D. Lukin & Liang Jiang
       https://www.nature.com/articles/srep20463
- Optimizing quantum noise-induced reservoir computing for nonlinear and chaotic time series prediction - Daniel Fry, Amol Deshmukh, Samuel Yen-Chi Chen, Vladimir Rastunkov, Vanio Markov
        https://arxiv.org/abs/2303.05488
- Option Pricing using Quantum Computers Nikitas Stamatopoulos, Daniel J. Egger, Yue Sun, Christa Zoufal2,3, Raban Iten2,3, Ning Shen1,
and Stefan Woerner
       https://arxiv.org/abs/1905.02666
- Phase sensitivity at the Heisenberg limit in an SU(1,1) interferometer via parity detection - Dong Li, Bryan T. Gard, Yang Gao3, Chun-Hua Yuan1, Weiping Zhang1, Hwang Lee, Jonathan P. Dowling
       https://arxiv.org/abs/1603.09019
- Photonic resource state generation from a minimal number of quantum emitters - Bikun Li, Sophia E. Economou, and Edwin Barnes     
       https://www.nature.com/articles/s41534-022-00522-6
- Position paper: Green Networking Metrics - draft-cx-green-metrics
       https://github.com/intarchboard/e-impact-workshop-public/blob/main/papers/Clemm-Dong-Mirsky-Ciavaglia-Tantsura-Odini_Green-Networking-Metrics.pdf
- Practical randomness and privacy amplification - Cameron Foreman, Sherilyn Wright, Alec Edgington, Mario Berta, Florian J. Curchod
       https://arxiv.org/abs/2009.06551
- Predicting Many Properties of a Quantum System from Very Few Measurements - Hsin-Yuan Huang, Richard Kueng, John Preskill
       https://arxiv.org/abs/2002.08953
- Programmable Heisenberg interactions between Floquet qubits - Long B. Nguyen, Yosep Kim, Akel Hashim, Noah Goss, Brian Marinelli, ... 
       https://arxiv.org/abs/2211.10383
- Proposal for room-temperature quantum repeaters with nitrogen-vacancy centers and optomechanics - Jia-Wei Ji, Yu-Feng Wu, Stephen C. Wein, ...
       https://arxiv.org/abs/2012.06687
- Protocols for creating and distilling multipartite GHZ states with Bell pairs - Sébastian de Bone, Runsheng Ouyang, Kenneth Goodenough, David Elkouss
       https://arxiv.org/abs/2010.12259
- Quantum Data Center: Theories and Applications - Junyu Liu, Connor T. Hann, and Liang Jiang1
       https://arxiv.org/abs/2207.14336
- Quantum Internet Protocol Stack a Comprehensive Survey - Jessica Illiano, Marcello Caleffi, Antonio Manzalini, Angela Sara Cacciapuoti
       https://arxiv.org/abs/2202.10894
- Quantum Particles and Classical Particles - Nathan Rosen
       https://link.springer.com/article/10.1007/BF00735376
- Quantum principal component analysis - Seth Lloyd, Masoud Mohseni and Patrick Rebentrost
       https://www.nature.com/articles/nphys3029#Sec2
- Quantum simulator enables first microscopic observation of charge carriers pairing
       https://www.mpq.mpg.de/6803661/01-magnetic-pairing
- Quantum states with Einstein-Podolsky-Rosen correlations admitting a hidden-variable model - Reinhard F. Werner
       https://journals.aps.org/pra/pdf/10.1103/PhysRevA.40.4277
- Quantum Support Vector Machine for Big Data Classification
       https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.113.130503
- Quantum supremacy using a programmable superconducting processor - Frank Arute1, Kunal Arya1, Ryan Babbush1, Dave Bacon
       https://www.nature.com/articles/s41586-019-1666-5
- Quantum Switch for the Quantum Internet: Noiseless Communications through Noisy Channels - Marcello Caleffi, Angela Sara Cacciapuoti
       https://arxiv.org/abs/1907.07432
- Quantum advantage in learning from experiments - Hsin-Yuan Huang, Michael Broughton, Jordan Cotler, Sitan Chen, Jerry Li, ...
       https://arxiv.org/abs/2112.00778
- Quantum communications and cryptography - Alexander V. Sergienko
       https://people.bu.edu/alexserg/Impression_Book.pdf
- Quantum computational advantage using photons - Han-Sen Zhong, Hui Wang, Yu-Hao Deng, Ming-Cheng Chen, Li-Chao Peng, Yi-Han Luo, Jian Qin, ...
       https://www.science.org/doi/10.1126/science.abe8770
- Quantum computational advantage with a programmable photonic processor - Lars S. Madsen, Fabian Laudenbach, Mohsen Falamarzi. Askarani, ...
       https://www.nature.com/articles/s41586-022-04725-x
- Quantum computing with photons - introduction to the circuit model, the one way quantum computer, and the fundamental principles of photonic experiments 
       https://iopscience.iop.org/article/10.1088/0953-4075/48/8/083001
- Quantum Computing - Andrew Steane
       https://arxiv.org/abs/quant-ph/9708022
- Quantum information processing with bosonic qubits in circuit QED - Atharv Joshi, Kyungjoo Noh, and Yvonne Y Gao
       https://iopscience.iop.org/article/10.1088/2058-9565/abe989/pdf
- Quantum readout error mitigation via deep learning - Jihye Kim, Byungdu Oh, Yonuk Chong, Euyheon Hwang, and Daniel K Park
       https://iopscience.iop.org/article/10.1088/1367-2630/ac7b3d
- Quantum walks a comprehensive review - Salvador E. Venegas-Andraca
       https://arxiv.org/abs/1201.4780
- Quantum-Enhanced Data Classification with a Variational Entangled Sensor Network - Yi Xia, Wei Li, Quntao Zhuang, Zheshen Zhang
       https://arxiv.org/abs/2006.11962
- Quantum Long Short-Term Memory - Samuel Yen-Chi Chen, Shinjae Yoo, Yao-Lung L. Fang
       https://arxiv.org/abs/2009.01783
- Rate limits in quantum networks with lossy repeaters - Riccardo Laurenza, Nathan Walk, Jens Eisert and Stefao Pirandola
       https://arxiv.org/pdf/2110.10168.pdf
- Real-time quantum error correction beyond break-even
       https://arxiv.org/abs/2211.09116
- Realization of Real-Time Fault-Tolerant Quantum Error Correction - C. Ryan-Anderson, J. G. Bohnet, K. Lee, D. Gresh, A. Hankin, J. P. Gaebler, Francois, A. Chernoguzov, ...
       https://journals.aps.org/prx/abstract/10.1103/PhysRevX.11.041058
- Reducing Green House Gas Emissions With Congestion Control - Michael Welzl, Ozgu Alay, Peyman Teymoori, Safiqul Islam
       https://github.com/intarchboard/e-impact-workshop-public/blob/main/papers/Welzel-Alay-Teymoori-Islam_Reducing-Green-House-Gas-Emissions-With-Congestion-Control-v2.pdf
- Request_Scheduling_in_Quantum_Networks - C. Cicconetti, M. Conti, and A. Passarella
       https://www.researchgate.net/publication/352621787_Request_Scheduling_in_Quantum_Networks
- Room temperature quantum key distribution characteristics of low‑noise InGaAs/InP single‑photon avalanche diode - Soo‑Hyun Baek, Seung‑Chul Yang1, Chan‑Yong Park
       https://link.springer.com/article/10.1007/s40042-021-00111-4
- Scaling silicon-based quantum computing using CMOS technology - M. F. Gonzalez-Zalba, S. de Franceschi, E. Charbon, T. Meunier, M. Vinet, A. S. Dzurak
       https://arxiv.org/abs/2011.11753
- Scheme for reducing decoherence in quantum computer memory, Peter W. Shor
       https://www.cs.miami.edu/home/burt/learning/Csc670.052/pR2493_1.pdf
- SeQUeNCe a customizable discrete-event simulator of quantum networks - Xiaoliang Wu, Alexander Kolar, Joaquin Chung, Dong Jin,, Tian Zhong, ...
       https://arxiv.org/abs/2009.12000
- Simple Proof of Security of the BB84 Quantum Key Distribution Protocol -Peter W. Shor, John Preskill
       https://arxiv.org/abs/quant-ph/0003004
- Solitons near avoided mode crossings in χ(2) nanowaveguides - William R. Rowe, Andrey V. Gorbach, Dmitry V. Skryabin
       https://arxiv.org/abs/2108.08563
- Stabilizer Codes and Quantum Error Correction -Thesis by Daniel Gottesman
       https://arxiv.org/abs/quant-ph/9705052
- Stim: a fast stabilizer circuit simulator -Craig Gidney
       https://arxiv.org/abs/2103.02202v3
- Subsystem codes with high thresholds by gauge fixing and reduced qubit overhead - Oscar Higgott, Nikolas P. Breuckmann
       https://arxiv.org/abs/2010.09626
- Surface codes: Towards practical large-scale quantum computation - Austin G. Fowler, Matteo Mariantoni, John M. Martinis and Andrew N. Cleland
     https://arxiv.org/abs/1208.0928   
- Symmetry-invariant quantum machine learning force fields - Isabel Nha Minh Le, Oriel Kiss, Julian Schuhmacher, Ivano Tavernelli, Francesco Tacchino
        https://arxiv.org/abs/2311.11362
- Teleportation of entanglement over 143 km - Thomas Herbst, Thomas Scheidl, Matthias Fink, Johannes Handsteiner, Bernhard Wittmann, Rupert Ursin, Anton Zeilinger
       https://arxiv.org/abs/1403.0009
- The Computational and Latency Advantage of Quantum Communication Networks - Roberto Ferrara, Riccardo Bassoli, Christian Deppe, Frank H.P. Fitzek and Holger Boche
       https://arxiv.org/pdf/2106.03360.pdf
- The Physical Implementation of Quantum Computation
       https://arxiv.org/abs/quant-ph/0002077
- The SWAP test and the Hong-Ou-Mandel effect are equivalent - Juan Carlos Garcia-Escartin, Pedro Chamorro-Posada
       https://arxiv.org/abs/1303.6814
- The Toric Code, Paul Herringer
       https://www.physics.rutgers.edu/grad/602/Lectures/JC_Presentations/0419/Intro_Toric_Code.pdf
- The information-theoretic foundation of thermodynamic work extraction - Chiara Marletto
       https://arxiv.org/abs/2009.04588
- The role of quantum information in thermodynamics ~ a topical review - John Goold, Marcus Huber, Arnau Riera, L´ıdia del Rio, and Paul Skrzypczyk
       https://arxiv.org/abs/1505.07835
- The_Virtual_Quantum_Optics_Laboratory - Brian R. La Cour, Maria Maynard, Parth Shroff, Gabriel Ko, Evan Ellis
       https://arxiv.org/abs/2105.07300
- Topological quantum memory - Eric Dennis,Alexei Kitaev,Andrew Landahl,and John Preskill
       https://arxiv.org/abs/quant-ph/0110143
- Paving the Way towards 800 Gbps Quantum-Secured Optical Channel Deployment - Farzam Toudeh-Fallah, Marco Pistoia, Yasushi Kawakura,...
       https://arxiv.org/abs/2202.07764
- Transitioning organizations to post-quantum cryptography - David Joseph1, Rafael Misoczki2, Marc Manzano1, Joe Tricot1, Fernando Dominguez, ...
       https://www.nature.com/articles/s41586-022-04623-2
- Two-photon interference the Hong-Ou-Mandel effect - FrédÉric Bouchard, Alicia Sit, Yingwen Zhang, Robert Fickler, Filippo M. Miatto,...
       https://arxiv.org/abs/2006.09335
- Universal and operational benchmarking of quantum memories - Xiao Yuan, Yunchao Liu, Qi Zhao, Bartosz Regula, Jayne Thompson and Mile Gu
       https://bartoszregula.me/pdf/s41534-021-00444-9.pdf
- Why Philosophers Should Care About Computational Complexity - Scott Aaronson
       https://arxiv.org/abs/1108.1791
- lambeq: An Efficient High-Level Python Library for Quantum NLP
       https://arxiv.org/abs/2110.04236

## End of 2023 dump 
### I will try to alphabetize this after the 2024 exam season
Quantum mechanics with real numbers: entanglement, superselection rules and gauges - Vlatko Vedral
https://arxiv.org/pdf/2308.05473.pdf

Interference in Quantum Field Theory: Detecting Ghosts with Phases - Chiara Marletto, Vlatko Vedral
https://onlinelibrary.wiley.com/doi/full/10.1002/andp.202200530

Observable Thermalization: Theory, Numerical and Analytical Evidence
Lodovico Scarpa, Fabio Anza,Vlatko Vedral
https://arxiv.org/pdf/2309.15173.pdf

Comparing coherent and incoherent models for quantum homogenization
Anna Beever, Maria Violaris, Chiara Marletto, and Vlatko Vedral
https://arxiv.org/pdf/2309.15741.pdf

Conservation Laws Reveal the Quantumness of Gravity - Tianfeng Feng, Chiara Marletto, Vlatko Vedral
https://arxiv.org/abs/2311.08971

Locality in the Schr ̈odinger Picture of Quantum Mechanics - Vlatko Vedral
https://arxiv.org/pdf/2312.04701.pdf

Entanglement in Many-Body Systems - Luigi Amico, Rosario Fazio, Vlatko Vedral
https://arxiv.org/pdf/quant-ph/0703044.pdf

The Everything-Is-a-Quantum-Wave Interpretation of Quantum Physics - Vlatko Vedral
https://www.mdpi.com/2624-960X/5/2/31

Error Correction of Quantum Algorithms: Arbitrarily Accurate Recovery Of Noisy Quantum Signal Processing - Andrew K. Tan, Yuan Liu, Minh C. Tran, Isaac L. Chuang
https://arxiv.org/pdf/2301.08542.pdf

Practical Benchmarking of Randomized Measurement Methods for Quantum Chemistry Hamiltonians - Arkopal Dutt, et.al 
https://arxiv.org/pdf/2312.07497.pdf

Single-shot Quantum Signal Processing Interferometry - Jasmine Sinanan-Singh, Gabriel L. Mintzer, Isaac L. Chuang, and Yuan Liu
https://arxiv.org/pdf/2311.13703.pdf

Resource savings from fault-tolerant circuit design - Andrew K. Tan, Isaac L. Chuang
https://arxiv.org/pdf/2311.02132.pdf

Active learning of quantum system Hamiltonians yields query advantage - Arkopal Dutt, et.al 
https://journals.aps.org/prresearch/pdf/10.1103/PhysRevResearch.5.033060

Power of sequential protocols in hidden quantum channel discrimination - Sho Sugiura, et.al 
https://arxiv.org/pdf/2304.02053.pdf

Noisy dynamical systems evolve error correcting codes and modularity - Trevor McCourt, Ila R. Fiete, and Isaac L. Chuang
https://arxiv.org/pdf/2303.14448.pdf

Bootstrap Embedding on a Quantum Computer -Yuan Liu, et.al.
https://arxiv.org/pdf/2301.01457.pdf

Deep Learning with Coherent Nanophotonic Circuits - Yichen Shen
https://arxiv.org/pdf/1610.02365.pdf

Solid-state single-photon emitters - Igor Aharonovich, Dirk Englund and Milos Toth
http://ciqm.harvard.edu/uploads/2/3/3/4/23349210/aharanovich_2016.pdf

Advances in Quantum Cryptography - S. Pirandola, et.al 
https://arxiv.org/pdf/1906.01645.pdf

Tutorial: Remote entanglement protocols for stationary qubits with photonic interfaces - Hans K.C. Beukers, et.al.
https://arxiv.org/pdf/2310.19878.pdf

Large-scale optical characterization of solid-state quantum emitters - Madison Sutula, et. al.
https://arxiv.org/pdf/2210.13643.pdf

Electrical Tuning of Neutral and Charged Excitons with 1-nm Gate - Jawaher Almutlaq, et. al.
https://arxiv.org/pdf/2310.19895.pdf

Quantum Optical Neural Networks (Patent Application)
https://patentimages.storage.googleapis.com/fa/61/94/ec20dc003a6517/US20200372334A1.pdf

Quantum algorithm for linear systems of equations - Aram W. Harrow, Avinatan Hassidim, and Seth Lloyd
https://arxiv.org/pdf/0811.3171.pdf

Supervised learning with quantum enhanced feature spaces - Vojtech Havlicek, et.al 
https://arxiv.org/pdf/1804.11326.pdf

Quantum Computational Supremacy - Aram W. Harrow, Ashley Montanaro
https://arxiv.org/pdf/1809.07442.pdf

18th Conference on the Theory of Quantum Computation, Communication and Cryptography
https://inspirehep.net/files/36042b35a0a8b68d0c63390592af9491

Exponential speedups for quantum walks in random hierarchical graphs - Shankar Balasubramanian, Tongyang Li, and Aram Harrow
https://arxiv.org/abs/2307.15062

Quantum computing at the frontiers of biological sciences - Prashant S. Emani, et. al.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8254820/
`

This is the full README list. I believe it contains over 100 papers

**Comment by DarkStarStrix** [comment]
Thanks

**Comment by DarkStarStrix** [comment]
Hey maria sorry I haven't been able to get this task done. I have been busy with moving and other work. I will try next week

**Comment by mgg39** [comment]
no worries :)

**Comment by DarkStarStrix** [comment]
Hey maria another update I'm realizing that this will be extraordinarily hard I'm not sure when I will be able to get it done There's too much read but I'll try again

**Pull request closed without merging**
